/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaFormMedico;

/**
 *
 * @author Tiemy Shibuya
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemvindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadMed = new javax.swing.JButton();
        jButtoncadPac = new javax.swing.JButton();
        jButtoncadEnf = new javax.swing.JButton();
        jLabelCadastro = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabelSistemade = new javax.swing.JLabel();
        jButtonfecharBemvindo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCadMédico = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeira = new javax.swing.JMenuItem();
        jMenuItemCadPaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemvindo.setTitle("Bem-vindo");
        jInternalFrameBemvindo.setVisible(true);
        jInternalFrameBemvindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonCadMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico.png"))); // NOI18N
        jButtonCadMed.setToolTipText("Médicos");
        jButtonCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadMed);
        jButtonCadMed.setBounds(10, 40, 60, 60);

        jButtoncadPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButtoncadPac.setToolTipText("Pacientes");
        jButtoncadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadPacActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtoncadPac);
        jButtoncadPac.setBounds(180, 40, 70, 60);

        jButtoncadEnf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfermeira.png"))); // NOI18N
        jButtoncadEnf.setToolTipText("Enfermeiras");
        jButtoncadEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadEnfActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtoncadEnf);
        jButtoncadEnf.setBounds(90, 40, 70, 60);

        jLabelCadastro.setText("Cadastro");
        jPanelInternal.add(jLabelCadastro);
        jLabelCadastro.setBounds(10, 10, 70, 30);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gradiente-azul-claro-fundo.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 590, 250);

        jInternalFrameBemvindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 50, 600, 250);

        jLabelSistemade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSistemade.setText("Sistema de gerenciamento de:");
        jInternalFrameBemvindo.getContentPane().add(jLabelSistemade);
        jLabelSistemade.setBounds(10, 10, 240, 22);

        jButtonfecharBemvindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonfecharBemvindo.setToolTipText("Fechar tela bem-vindo");
        jButtonfecharBemvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfecharBemvindoActionPerformed(evt);
            }
        });
        jInternalFrameBemvindo.getContentPane().add(jButtonfecharBemvindo);
        jButtonfecharBemvindo.setBounds(530, 0, 40, 40);

        getContentPane().add(jInternalFrameBemvindo);
        jInternalFrameBemvindo.setBounds(0, 80, 600, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 600, 410);

        jMenu1.setText("Perfil");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        jMenuItemCadMédico.setText("Médico");
        jMenuItemCadMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMédicoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCadMédico);

        jMenuItemCadEnfermeira.setText("Enfermeira");
        jMenu2.add(jMenuItemCadEnfermeira);

        jMenuItemCadPaciente.setText("Paciente");
        jMenu2.add(jMenuItemCadPaciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");

        jMenuItemSair.setText("sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(616, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMédicoActionPerformed
       TelaFormMedico tela = new TelaFormMedico();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMédicoActionPerformed

    private void jButtonCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedActionPerformed
        TelaFormMedico tela = new TelaFormMedico();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadMedActionPerformed

    private void jButtoncadEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadEnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncadEnfActionPerformed

    private void jButtoncadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncadPacActionPerformed

    private void jButtonfecharBemvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfecharBemvindoActionPerformed
       jInternalFrameBemvindo.dispose();
    }//GEN-LAST:event_jButtonfecharBemvindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadMed;
    private javax.swing.JButton jButtoncadEnf;
    private javax.swing.JButton jButtoncadPac;
    private javax.swing.JButton jButtonfecharBemvindo;
    private javax.swing.JInternalFrame jInternalFrameBemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelSistemade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadEnfermeira;
    private javax.swing.JMenuItem jMenuItemCadMédico;
    private javax.swing.JMenuItem jMenuItemCadPaciente;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
