/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Tiemy Shibuya
 */
public class TelaPerfil extends javax.swing.JFrame {

    /**
     * Creates new form TelaPerfil
     */
    public TelaPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldEnd = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 120, 120);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("Nome completo:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(170, 120, 140, 22);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCPF.setText("CPF:");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(170, 200, 50, 22);

        jLabelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTel.setText("Telefone:");
        getContentPane().add(jLabelTel);
        jLabelTel.setBounds(170, 290, 90, 22);

        jLabelEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEnd.setText("Endereço:");
        getContentPane().add(jLabelEnd);
        jLabelEnd.setBounds(170, 440, 90, 22);

        jLabelRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRG.setText("RG:");
        getContentPane().add(jLabelRG);
        jLabelRG.setBounds(490, 130, 34, 14);

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDataNasc.setText("Data de nascimento:");
        getContentPane().add(jLabelDataNasc);
        jLabelDataNasc.setBounds(170, 360, 170, 22);

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(490, 200, 50, 22);
        getContentPane().add(jFormattedTextFieldNome);
        jFormattedTextFieldNome.setBounds(170, 150, 240, 30);
        getContentPane().add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(170, 230, 240, 30);
        getContentPane().add(jFormattedTextFieldTel);
        jFormattedTextFieldTel.setBounds(170, 310, 240, 30);
        getContentPane().add(jFormattedTextFieldDataNasc);
        jFormattedTextFieldDataNasc.setBounds(170, 390, 240, 30);
        getContentPane().add(jFormattedTextFieldEnd);
        jFormattedTextFieldEnd.setBounds(170, 470, 240, 30);
        getContentPane().add(jFormattedTextFieldRG);
        jFormattedTextFieldRG.setBounds(490, 150, 200, 30);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", " " }));
        getContentPane().add(jComboBoxSexo);
        jComboBoxSexo.setBounds(490, 230, 80, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 80);

        setSize(new java.awt.Dimension(732, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnd;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
