/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Tiemy Shibuya
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdministrador = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButtonAjuda = new javax.swing.JToggleButton();
        jButtonMensagem = new javax.swing.JButton();
        jLabelNomeAdmin = new javax.swing.JLabel();
        jLabelFotoAdmin = new javax.swing.JLabel();
        jButtonMedico = new javax.swing.JButton();
        jButtonEnfermeira = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelAdministrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAdministrador.setText("ADMINISTRADOR");
        getContentPane().add(jLabelAdministrador);
        jLabelAdministrador.setBounds(680, 10, 110, 17);

        jButtonSair.setBackground(new java.awt.Color(153, 153, 255));
        jButtonSair.setForeground(new java.awt.Color(204, 204, 255));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorder(null);
        jButtonSair.setBorderPainted(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(10, 540, 40, 40);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil.png"))); // NOI18N
        jToggleButton2.setText(" Pefil");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(10, 160, 140, 40);

        jToggleButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ajuda.png"))); // NOI18N
        jToggleButtonAjuda.setText("Ajuda & Sobre");
        getContentPane().add(jToggleButtonAjuda);
        jToggleButtonAjuda.setBounds(10, 210, 140, 40);

        jButtonMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mensagem.png"))); // NOI18N
        jButtonMensagem.setToolTipText("Mensagem");
        getContentPane().add(jButtonMensagem);
        jButtonMensagem.setBounds(730, 550, 50, 30);

        jLabelNomeAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeAdmin.setText("Nome do admin.");
        getContentPane().add(jLabelNomeAdmin);
        jLabelNomeAdmin.setBounds(30, 100, 160, 17);

        jLabelFotoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/administrador.png"))); // NOI18N
        getContentPane().add(jLabelFotoAdmin);
        jLabelFotoAdmin.setBounds(50, 30, 90, 70);

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico.png"))); // NOI18N
        jButtonMedico.setToolTipText("Médico");
        jButtonMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMedicoMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMedicoMouseReleased(evt);
            }
        });
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMedico);
        jButtonMedico.setBounds(220, 170, 60, 60);

        jButtonEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfermeira.png"))); // NOI18N
        jButtonEnfermeira.setToolTipText("Enfermeira");
        getContentPane().add(jButtonEnfermeira);
        jButtonEnfermeira.setBounds(310, 170, 60, 60);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButtonPaciente.setToolTipText("Paciente");
        getContentPane().add(jButtonPaciente);
        jButtonPaciente.setBounds(480, 170, 60, 60);

        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRelatorio.setToolTipText("Relatório");
        getContentPane().add(jButtonRelatorio);
        jButtonRelatorio.setBounds(650, 170, 60, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 400, 460, 90);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(200, 360, 280, 20);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jToggleButton1.setText(" Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(510, 360, 120, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastrar:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 130, 70, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pesquisar funcionário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 320, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pacientes:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 130, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Relatório:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 130, 80, 17);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 160, 560);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 30);

        setSize(new java.awt.Dimension(816, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButtonMedicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicoMouseEntered

    private void jButtonMedicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnfermeira;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonMensagem;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelFotoAdmin;
    private javax.swing.JLabel jLabelNomeAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButtonAjuda;
    // End of variables declaration//GEN-END:variables
}
