package view;

/**
 *
 * @author Tiemy Shibuya
 */
public class TelaPerfilPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPerfil
     */
    public TelaPerfilPaciente(String usuario) {
        initComponents();
        jLabelNome.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeC = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldEnd = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jPanelFundoSuperior = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNomeC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeC.setText("Nome completo:");
        getContentPane().add(jLabelNomeC);
        jLabelNomeC.setBounds(210, 100, 140, 22);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCPF.setText("CPF:");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(210, 180, 50, 22);

        jLabelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTel.setText("Telefone:");
        getContentPane().add(jLabelTel);
        jLabelTel.setBounds(210, 260, 90, 22);

        jLabelEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEnd.setText("Endereço:");
        getContentPane().add(jLabelEnd);
        jLabelEnd.setBounds(210, 430, 90, 22);

        jLabelRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRG.setText("RG:");
        getContentPane().add(jLabelRG);
        jLabelRG.setBounds(530, 100, 34, 14);

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDataNasc.setText("Data de nascimento:");
        getContentPane().add(jLabelDataNasc);
        jLabelDataNasc.setBounds(210, 350, 170, 22);

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(530, 180, 50, 22);
        getContentPane().add(jFormattedTextFieldNome);
        jFormattedTextFieldNome.setBounds(210, 130, 240, 30);
        getContentPane().add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(210, 210, 240, 30);

        jFormattedTextFieldTel.setText("(  )  -");
        jFormattedTextFieldTel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextFieldTel);
        jFormattedTextFieldTel.setBounds(210, 290, 240, 30);

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextFieldDataNasc);
        jFormattedTextFieldDataNasc.setBounds(210, 380, 240, 30);
        getContentPane().add(jFormattedTextFieldEnd);
        jFormattedTextFieldEnd.setBounds(210, 460, 300, 30);
        getContentPane().add(jFormattedTextFieldRG);
        jFormattedTextFieldRG.setBounds(530, 130, 200, 30);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        jLabelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jPanel2.add(jLabelPerfil);
        jLabelPerfil.setBounds(20, 30, 100, 100);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome do paciente");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(20, 130, 110, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar);
        jButtonVoltar.setBounds(30, 490, 89, 33);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 30, 140, 590);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(730, 530, 40, 30);

        jPanelFundoSuperior.setBackground(new java.awt.Color(102, 102, 255));
        jPanelFundoSuperior.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Perfil do paciente");
        jPanelFundoSuperior.add(jLabel3);
        jLabel3.setBounds(670, 10, 120, 20);

        getContentPane().add(jPanelFundoSuperior);
        jPanelFundoSuperior.setBounds(0, 0, 790, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(540, 220, 190, 30);

        setSize(new java.awt.Dimension(799, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnd;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeC;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFundoSuperior;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
